### ISSUE TITLE
Can you please add a license to this repo?

### ISSUE THREAD

**Issue by Yixiao-Zhang** [storyofthewolf/ExoCAM#1]
Thank you for putting your codes on Github.

However, according to [GitHub's licensing help page](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license), we can fork the repository and view the code, but nothing more. So, the absence of a license can be a problem if someone wants to use this repo in any form.

**Comment by storyofthewolf** [comment]
sorry for only taking 9 months to do this.  I am sure you have probably moved on in your research.  A license has been added.  Cheers, Eric
